services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel
    ports:
      - 80:80
      - 443:443
    environment:
      - LARAVEL_SERVER_NAME=${LARAVEL_SERVER_NAME}
      - NEXTJS_SERVER_NAME=${NEXTJS_SERVER_NAME}
    volumes:
      - ./src-laravel:/src-laravel
      - ./docker/nginx/mkcerts:/etc/ssl/certs

  laravel:
    container_name: "laravel"
    build:
      context: ./docker/php
    depends_on:
      - mysql
    ports:
      - "5173:5173"
    volumes:
      - ./src-laravel:/src-laravel
      - ./src-laravel/vendor:/src-laravel/vendor
      - ./src-laravel/node_modules:/src-laravel/node_modules
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/nginx/mkcerts:/etc/ssl/certs

  mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 16379:6379

  mail:
    image: axllent/mailpit:v1.8
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025

  nextjs:
    container_name: "nextjs"
    build:
      context: ./docker/nextjs
    depends_on:
      - nginx
    ports:
      - 3000:3000
    volumes:
      - ./src-next:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}